# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from camera/pos_message.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class pos_message(genpy.Message):
  _md5sum = "1d9e4de796d3278b9e92378ad269bd1e"
  _type = "camera/pos_message"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time time
float32 relate_E #正东方向差距 单位 米
float32 relate_N #正北方向差距 单位 米
float32 tar_lat
float32 tar_lon"""
  __slots__ = ['time','relate_E','relate_N','tar_lat','tar_lon']
  _slot_types = ['time','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,relate_E,relate_N,tar_lat,tar_lon

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pos_message, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = genpy.Time()
      if self.relate_E is None:
        self.relate_E = 0.
      if self.relate_N is None:
        self.relate_N = 0.
      if self.tar_lat is None:
        self.tar_lat = 0.
      if self.tar_lon is None:
        self.tar_lon = 0.
    else:
      self.time = genpy.Time()
      self.relate_E = 0.
      self.relate_N = 0.
      self.tar_lat = 0.
      self.tar_lon = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I4f().pack(_x.time.secs, _x.time.nsecs, _x.relate_E, _x.relate_N, _x.tar_lat, _x.tar_lon))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.time is None:
        self.time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.time.secs, _x.time.nsecs, _x.relate_E, _x.relate_N, _x.tar_lat, _x.tar_lon,) = _get_struct_2I4f().unpack(str[start:end])
      self.time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I4f().pack(_x.time.secs, _x.time.nsecs, _x.relate_E, _x.relate_N, _x.tar_lat, _x.tar_lon))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.time is None:
        self.time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.time.secs, _x.time.nsecs, _x.relate_E, _x.relate_N, _x.tar_lat, _x.tar_lon,) = _get_struct_2I4f().unpack(str[start:end])
      self.time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I4f = None
def _get_struct_2I4f():
    global _struct_2I4f
    if _struct_2I4f is None:
        _struct_2I4f = struct.Struct("<2I4f")
    return _struct_2I4f
