// Generated by gencpp from file camera/detect_msg.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_DETECT_MSG_H
#define CAMERA_MESSAGE_DETECT_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct detect_msg_
{
  typedef detect_msg_<ContainerAllocator> Type;

  detect_msg_()
    : lat(0.0)
    , lon(0.0)  {
    }
  detect_msg_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , lon(0.0)  {
  (void)_alloc;
    }



   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;





  typedef boost::shared_ptr< ::camera::detect_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::detect_msg_<ContainerAllocator> const> ConstPtr;

}; // struct detect_msg_

typedef ::camera::detect_msg_<std::allocator<void> > detect_msg;

typedef boost::shared_ptr< ::camera::detect_msg > detect_msgPtr;
typedef boost::shared_ptr< ::camera::detect_msg const> detect_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::detect_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::detect_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera::detect_msg_<ContainerAllocator1> & lhs, const ::camera::detect_msg_<ContainerAllocator2> & rhs)
{
  return lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera::detect_msg_<ContainerAllocator1> & lhs, const ::camera::detect_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera::detect_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::detect_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::detect_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::detect_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::detect_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::detect_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::detect_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deb12644498d4b5511a84dbd9af1e283";
  }

  static const char* value(const ::camera::detect_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdeb12644498d4b55ULL;
  static const uint64_t static_value2 = 0x11a84dbd9af1e283ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::detect_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/detect_msg";
  }

  static const char* value(const ::camera::detect_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::detect_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lat\n"
"float64 lon\n"
;
  }

  static const char* value(const ::camera::detect_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::detect_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.lon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detect_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::detect_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::detect_msg_<ContainerAllocator>& v)
  {
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_DETECT_MSG_H
