// Generated by gencpp from file camera/gimbal_msg.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_GIMBAL_MSG_H
#define CAMERA_MESSAGE_GIMBAL_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct gimbal_msg_
{
  typedef gimbal_msg_<ContainerAllocator> Type;

  gimbal_msg_()
    : pos_x(0.0)
    , pos_y(0.0)
    , height(0.0)  {
    }
  gimbal_msg_(const ContainerAllocator& _alloc)
    : pos_x(0.0)
    , pos_y(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::camera::gimbal_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::gimbal_msg_<ContainerAllocator> const> ConstPtr;

}; // struct gimbal_msg_

typedef ::camera::gimbal_msg_<std::allocator<void> > gimbal_msg;

typedef boost::shared_ptr< ::camera::gimbal_msg > gimbal_msgPtr;
typedef boost::shared_ptr< ::camera::gimbal_msg const> gimbal_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::gimbal_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::gimbal_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera::gimbal_msg_<ContainerAllocator1> & lhs, const ::camera::gimbal_msg_<ContainerAllocator2> & rhs)
{
  return lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera::gimbal_msg_<ContainerAllocator1> & lhs, const ::camera::gimbal_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera::gimbal_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::gimbal_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::gimbal_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::gimbal_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::gimbal_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::gimbal_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::gimbal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef9bdc0e9b0547b3ddcf9b4fb816ef5f";
  }

  static const char* value(const ::camera::gimbal_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef9bdc0e9b0547b3ULL;
  static const uint64_t static_value2 = 0xddcf9b4fb816ef5fULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::gimbal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/gimbal_msg";
  }

  static const char* value(const ::camera::gimbal_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::gimbal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_x\n"
"float32 pos_y\n"
"float32 height\n"
;
  }

  static const char* value(const ::camera::gimbal_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::gimbal_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gimbal_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::gimbal_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::gimbal_msg_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_GIMBAL_MSG_H
