// Generated by gencpp from file camera/neighbor_camera_data.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_NEIGHBOR_CAMERA_DATA_H
#define CAMERA_MESSAGE_NEIGHBOR_CAMERA_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct neighbor_camera_data_
{
  typedef neighbor_camera_data_<ContainerAllocator> Type;

  neighbor_camera_data_()
    : UAV_ID(0)
    , UAV_OBJ_X(0)
    , UAV_OBJ_Y(0)
    , latitude(0)
    , longitude(0)
    , altitude(0)  {
    }
  neighbor_camera_data_(const ContainerAllocator& _alloc)
    : UAV_ID(0)
    , UAV_OBJ_X(0)
    , UAV_OBJ_Y(0)
    , latitude(0)
    , longitude(0)
    , altitude(0)  {
  (void)_alloc;
    }



   typedef uint8_t _UAV_ID_type;
  _UAV_ID_type UAV_ID;

   typedef uint16_t _UAV_OBJ_X_type;
  _UAV_OBJ_X_type UAV_OBJ_X;

   typedef uint16_t _UAV_OBJ_Y_type;
  _UAV_OBJ_Y_type UAV_OBJ_Y;

   typedef uint32_t _latitude_type;
  _latitude_type latitude;

   typedef uint32_t _longitude_type;
  _longitude_type longitude;

   typedef uint16_t _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::camera::neighbor_camera_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::neighbor_camera_data_<ContainerAllocator> const> ConstPtr;

}; // struct neighbor_camera_data_

typedef ::camera::neighbor_camera_data_<std::allocator<void> > neighbor_camera_data;

typedef boost::shared_ptr< ::camera::neighbor_camera_data > neighbor_camera_dataPtr;
typedef boost::shared_ptr< ::camera::neighbor_camera_data const> neighbor_camera_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::neighbor_camera_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::neighbor_camera_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera::neighbor_camera_data_<ContainerAllocator1> & lhs, const ::camera::neighbor_camera_data_<ContainerAllocator2> & rhs)
{
  return lhs.UAV_ID == rhs.UAV_ID &&
    lhs.UAV_OBJ_X == rhs.UAV_OBJ_X &&
    lhs.UAV_OBJ_Y == rhs.UAV_OBJ_Y &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera::neighbor_camera_data_<ContainerAllocator1> & lhs, const ::camera::neighbor_camera_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera::neighbor_camera_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::neighbor_camera_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::neighbor_camera_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::neighbor_camera_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::neighbor_camera_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::neighbor_camera_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::neighbor_camera_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf9983e93e6a13e8480601768a9c54d4";
  }

  static const char* value(const ::camera::neighbor_camera_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf9983e93e6a13e8ULL;
  static const uint64_t static_value2 = 0x480601768a9c54d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::neighbor_camera_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/neighbor_camera_data";
  }

  static const char* value(const ::camera::neighbor_camera_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::neighbor_camera_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8   UAV_ID\n"
"#物体相对位置估计\n"
"uint16 UAV_OBJ_X\n"
"uint16 UAV_OBJ_Y\n"
"#无人机信息\n"
"uint32 latitude\n"
"uint32 longitude\n"
"uint16 altitude\n"
;
  }

  static const char* value(const ::camera::neighbor_camera_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::neighbor_camera_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.UAV_ID);
      stream.next(m.UAV_OBJ_X);
      stream.next(m.UAV_OBJ_Y);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct neighbor_camera_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::neighbor_camera_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::neighbor_camera_data_<ContainerAllocator>& v)
  {
    s << indent << "UAV_ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.UAV_ID);
    s << indent << "UAV_OBJ_X: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.UAV_OBJ_X);
    s << indent << "UAV_OBJ_Y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.UAV_OBJ_Y);
    s << indent << "latitude: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_NEIGHBOR_CAMERA_DATA_H
