// Generated by gencpp from file camera/pixel_msg.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PIXEL_MSG_H
#define CAMERA_MESSAGE_PIXEL_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct pixel_msg_
{
  typedef pixel_msg_<ContainerAllocator> Type;

  pixel_msg_()
    : time()
    , pixel_x(0.0)
    , pixel_y(0.0)  {
    }
  pixel_msg_(const ContainerAllocator& _alloc)
    : time()
    , pixel_x(0.0)
    , pixel_y(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _time_type;
  _time_type time;

   typedef float _pixel_x_type;
  _pixel_x_type pixel_x;

   typedef float _pixel_y_type;
  _pixel_y_type pixel_y;





  typedef boost::shared_ptr< ::camera::pixel_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::pixel_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pixel_msg_

typedef ::camera::pixel_msg_<std::allocator<void> > pixel_msg;

typedef boost::shared_ptr< ::camera::pixel_msg > pixel_msgPtr;
typedef boost::shared_ptr< ::camera::pixel_msg const> pixel_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::pixel_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::pixel_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera::pixel_msg_<ContainerAllocator1> & lhs, const ::camera::pixel_msg_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.pixel_x == rhs.pixel_x &&
    lhs.pixel_y == rhs.pixel_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera::pixel_msg_<ContainerAllocator1> & lhs, const ::camera::pixel_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera::pixel_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::pixel_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::pixel_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::pixel_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::pixel_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::pixel_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::pixel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92eab89a17307a1d310df233c30b69f6";
  }

  static const char* value(const ::camera::pixel_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92eab89a17307a1dULL;
  static const uint64_t static_value2 = 0x310df233c30b69f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::pixel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/pixel_msg";
  }

  static const char* value(const ::camera::pixel_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::pixel_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time time\n"
"float32 pixel_x\n"
"float32 pixel_y\n"
;
  }

  static const char* value(const ::camera::pixel_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::pixel_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.pixel_x);
      stream.next(m.pixel_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pixel_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::pixel_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::pixel_msg_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "pixel_x: ";
    Printer<float>::stream(s, indent + "  ", v.pixel_x);
    s << indent << "pixel_y: ";
    Printer<float>::stream(s, indent + "  ", v.pixel_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_PIXEL_MSG_H
