// Generated by gencpp from file camera/pos_message.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_POS_MESSAGE_H
#define CAMERA_MESSAGE_POS_MESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct pos_message_
{
  typedef pos_message_<ContainerAllocator> Type;

  pos_message_()
    : time()
    , relate_E(0.0)
    , relate_N(0.0)
    , tar_lat(0.0)
    , tar_lon(0.0)  {
    }
  pos_message_(const ContainerAllocator& _alloc)
    : time()
    , relate_E(0.0)
    , relate_N(0.0)
    , tar_lat(0.0)
    , tar_lon(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _time_type;
  _time_type time;

   typedef float _relate_E_type;
  _relate_E_type relate_E;

   typedef float _relate_N_type;
  _relate_N_type relate_N;

   typedef float _tar_lat_type;
  _tar_lat_type tar_lat;

   typedef float _tar_lon_type;
  _tar_lon_type tar_lon;





  typedef boost::shared_ptr< ::camera::pos_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::pos_message_<ContainerAllocator> const> ConstPtr;

}; // struct pos_message_

typedef ::camera::pos_message_<std::allocator<void> > pos_message;

typedef boost::shared_ptr< ::camera::pos_message > pos_messagePtr;
typedef boost::shared_ptr< ::camera::pos_message const> pos_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::pos_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::pos_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera::pos_message_<ContainerAllocator1> & lhs, const ::camera::pos_message_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.relate_E == rhs.relate_E &&
    lhs.relate_N == rhs.relate_N &&
    lhs.tar_lat == rhs.tar_lat &&
    lhs.tar_lon == rhs.tar_lon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera::pos_message_<ContainerAllocator1> & lhs, const ::camera::pos_message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera::pos_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::pos_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::pos_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::pos_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::pos_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::pos_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::pos_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d9e4de796d3278b9e92378ad269bd1e";
  }

  static const char* value(const ::camera::pos_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d9e4de796d3278bULL;
  static const uint64_t static_value2 = 0x9e92378ad269bd1eULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::pos_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/pos_message";
  }

  static const char* value(const ::camera::pos_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::pos_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time time\n"
"float32 relate_E #正东方向差距 单位 米\n"
"float32 relate_N #正北方向差距 单位 米\n"
"float32 tar_lat\n"
"float32 tar_lon\n"
;
  }

  static const char* value(const ::camera::pos_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::pos_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.relate_E);
      stream.next(m.relate_N);
      stream.next(m.tar_lat);
      stream.next(m.tar_lon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::pos_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::pos_message_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "relate_E: ";
    Printer<float>::stream(s, indent + "  ", v.relate_E);
    s << indent << "relate_N: ";
    Printer<float>::stream(s, indent + "  ", v.relate_N);
    s << indent << "tar_lat: ";
    Printer<float>::stream(s, indent + "  ", v.tar_lat);
    s << indent << "tar_lon: ";
    Printer<float>::stream(s, indent + "  ", v.tar_lon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_POS_MESSAGE_H
