// Generated by gencpp from file camera/servo_msg.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_SERVO_MSG_H
#define CAMERA_MESSAGE_SERVO_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct servo_msg_
{
  typedef servo_msg_<ContainerAllocator> Type;

  servo_msg_()
    : angle1(0.0)
    , angle2(0.0)  {
    }
  servo_msg_(const ContainerAllocator& _alloc)
    : angle1(0.0)
    , angle2(0.0)  {
  (void)_alloc;
    }



   typedef float _angle1_type;
  _angle1_type angle1;

   typedef float _angle2_type;
  _angle2_type angle2;





  typedef boost::shared_ptr< ::camera::servo_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::servo_msg_<ContainerAllocator> const> ConstPtr;

}; // struct servo_msg_

typedef ::camera::servo_msg_<std::allocator<void> > servo_msg;

typedef boost::shared_ptr< ::camera::servo_msg > servo_msgPtr;
typedef boost::shared_ptr< ::camera::servo_msg const> servo_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::servo_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::servo_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::camera::servo_msg_<ContainerAllocator1> & lhs, const ::camera::servo_msg_<ContainerAllocator2> & rhs)
{
  return lhs.angle1 == rhs.angle1 &&
    lhs.angle2 == rhs.angle2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::camera::servo_msg_<ContainerAllocator1> & lhs, const ::camera::servo_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::camera::servo_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::servo_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::servo_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::servo_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::servo_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::servo_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "343bc431207c2d7a78fcf1a862aeef25";
  }

  static const char* value(const ::camera::servo_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x343bc431207c2d7aULL;
  static const uint64_t static_value2 = 0x78fcf1a862aeef25ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/servo_msg";
  }

  static const char* value(const ::camera::servo_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle1\n"
"float32 angle2\n"
;
  }

  static const char* value(const ::camera::servo_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::servo_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle1);
      stream.next(m.angle2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::servo_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::servo_msg_<ContainerAllocator>& v)
  {
    s << indent << "angle1: ";
    Printer<float>::stream(s, indent + "  ", v.angle1);
    s << indent << "angle2: ";
    Printer<float>::stream(s, indent + "  ", v.angle2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_SERVO_MSG_H
